apiVersion: druid.apache.org/v1alpha1
kind: DruidIngestion
metadata:
  labels:
    app.kubernetes.io/name: druidingestion
    app.kubernetes.io/instance: druidingestion-sample
    app.kubernetes.io/part-of: druid-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: druid-operator
  name: druidingestion-sample
spec:
  # TODO(user): Add fields here
